config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pages, only: [:show]
  resources :products, only: [:index, :show]
  resources :line_items
  resources :carts
  resources :charges

  resources :search, only: [:index] do
    collection do 
      get 'results'
    end
  end
  
  get ':permalink', to: 'pages#permalink'
  get 'products', to: 'products#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

    validates :name, :description, :price, :stock, presence: true
    validates :name, length: { minimum: 3 }
    validates :description, length: {maximum: 500}
    validates :price, :stock, numericality: true

    mount_uploader :image, ImageUploader
    before_destroy :not_referenced_by_any_line_item

    belongs_to :category
    has_many :line_items

    private

    def not_refereced_by_any_line_item
        unless line_items.empty?
          errors.add(:base, "Line items present")
          throw :abort
        end
      end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order('name ASC').page(params[:page]).per(5)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="product">
    <p>
        <%= link_to product.name, product %> <%= number_to_currency(product.price) %> 
    </p>
</div>

app/views/products/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Our Products
      </h1>
    </div>
  </div>
</section>
<% end %>
<div class='field'>
      <%= form_tag(results_search_index_path, method: "get") do %>
        <%= label_tag 'category', 'Category:' %>
        <%= select_tag"category", options_from_collection_for_select(Category.all, "id", "name"), :include_blank => "All" %>
        <%= label_tag 'orderBy', 'Order By:' %>
        <%= select_tag"orderBy", options_for_select({"Name" => "1", "New" => "2", "Recently Update" =>"3"}) %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
<% end %>
</div>

<%= paginate @products %>

<div class="product-index-grid pt4">

  <% @products.each do |product| %>

    <div class="product border-light">

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>
      <small style="font-style:italic"> <%= product.category.name %> </small>

      <p class="has-text-gray fg pt1"><%= product.description %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>

    </div>
  </div>
  <% end %>
</div>

<%= paginate @products %>

app/views/products/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section product-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @product.name %></h1>

      <ul class="pv1">
        <% if @product.category.name? %>
        <li class="inline-block pr3"><%= @product.category.name %></li>
        <% end %>

      </ul>

      <div class="feature-image">
        <%= image_tag(@product.image.url) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @product.description %>

    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>
        <%= button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

</section>