config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pages, only: [:show]
  resources :products, only: [:index, :show]
  resources :line_items
  resources :carts
  resources :charges

  resources :search, only: [:index] do
    collection do 
      get 'results'
    end
  end
  
  get ':permalink', to: 'pages#permalink'
  get 'products', to: 'products#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
    
        if current_item
          current_item.increment(:quantity)
        else
          current_item = line_items.build(product_id: product.id)
        end
        current_item
      end
    
      def total_price
        line_items.to_a.sum { |item| item.total_price }
      end
    
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true

	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price.to_i * quantity.to_i
  end

end

app/models/page.rb
class Page < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, length: {minimum: 3 }
end

app/models/product.rb
class Product < ApplicationRecord

    validates :name, :description, :price, :stock, presence: true
    validates :name, length: { minimum: 3 }
    validates :description, length: {maximum: 500}
    validates :price, :stock, numericality: true

    mount_uploader :image, ImageUploader
    before_destroy :not_referenced_by_any_line_item

    belongs_to :category
    has_many :line_items

    private

    def not_refereced_by_any_line_item
        unless line_items.empty?
          errors.add(:base, "Line items present")
          throw :abort
        end
      end
end

app/models/province.rb
class Province < ApplicationRecord
    validates :name, :gst, :pst, presence: true
    validates :pst, :gst, numericality: true
  end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[show edit update destroy]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

class ChargesController < ApplicationController
  def new
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => params[:amount],
      :description => 'Rails customer',
      :currency    => 'usd'
    )
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :root
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @products = Product.all.order('created_at desc').limit(5)
  end

  def permalink
    @page = Page.find_by(permalink: params[:permalink])
    if @page.nil?
      redirect_to root_url
    else
      render :show
    end
  end

  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order('name ASC').page(params[:page]).per(5)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
  end

  def results
    if params[:category] == "" && params[:q] != nil && params[:orderBy] == "1"

      @products = Product.where('name LIKE ? OR description LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%").order("name ASC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] == "" && params[:orderBy] == "1"

      @products = Product.where('cast(category_id as text) LIKE ?', "#{params[:category]}").order("name ASC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] != nil && params[:orderBy] == "1"

      @products = Product.where('(name LIKE ? OR description LIKE ?) AND cast(category_id as text) LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%", "#{params[:category]}").order("name ASC").page(params[:page]).per(5)

    elsif params[:category] == "" && params[:q] != nil && params[:orderBy] == "2"

      @products = Product.where('name LIKE ? OR description LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%").order("created_at DESC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] == "" && params[:orderBy] == "2"

      @products = Product.where('cast(category_id as text) LIKE ?', "#{params[:category]}").order("created_at DESC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] != nil && params[:orderBy] == "2"

      @products = Product.where('(name LIKE ? OR description LIKE ?) AND cast(category_id as text) LIKE?', "%#{params[:q]}%", "%#{params[:q]}%", "#{params[:category]}").order("created_at DESC").page(params[:page]).per(5)

    elsif params[:category] == "" && params[:q] != nil && params[:orderBy] == "3"

      @products = Product.where('name LIKE ? OR description LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%").order("updated_at DESC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] == "" && params[:orderBy] == "3"

      @products = Product.where('cast(category_id as text) LIKE ?', "#{params[:category]}").order("updated_at DESC").page(params[:page]).per(5)

    elsif params[:category] != nil && params[:q] != nil && params[:orderBy] == "3"

      @products = Product.where('(name LIKE ? OR description LIKE ?) AND cast(category_id as text) LIKE?', "%#{params[:q]}%", "%#{params[:q]}%", "#{params[:category]}").order("updated_at DESC").page(params[:page]).per(5)

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def cart_count_over_one
    if total_cart_items > 0
      return "<span class='tag is-dark'>#{total_cart_items}</span>".html_safe
    end
  end

  def total_cart_items
     total = @cart.line_items.map { |item| item.quantity }.sum
     return total if total > 0
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Commerce Project</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Hyperlearn</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

            <% if total_cart_items %>
              <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
              <% end %>
            <% end %>

            <%= link_to "Products", products_path, class:"navbar-item button is-warning" %>
            <%= link_to "About", about_path, class:"navbar-item button is-warning"%>
            <%= link_to "Contact", contact_path, class:"navbar-item button is-warning"%>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/pages/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest careers
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="product-index-grid pt4">
  <% @products.each do |product| %>

    <div class="product border-light">

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>

      <p class="has-text-gray fg pt1"><%= product.description %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>

    </div>
  </div>
  <% end %>
</div>

app/views/pages/show.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       <%=@page.title%>
      </h1>
    </div>
  </div>
</section>
<% end %>

<div><%= @page.content %></div>